### ISSUE TITLE
Game crashing when potion IDs are over 127. Example is the pants from the water boss when you get the effect

### ISSUE THREAD

**Issue by GraysonUnitt** [TCLProject/ArsMagica2-5#11]
Whenever I have the AM2 potion IDs over 127 and I get one of the effects on me my game crashes. The easiest way to reproduce this is using the pants that drop from the water guardian. Tested with both Water Orbs and Archmage pants. Its a rendering issue of the debuff it looks like.
With Status Hud:
[crash-2023-06-28_19.28.14-client.txt](https://github.com/TCLProject/ArsMagica2-5/files/11900651/crash-2023-06-28_19.28.14-client.txt)
Without:
[crash-2023-06-28_19.35.10-client.txt](https://github.com/TCLProject/ArsMagica2-5/files/11900672/crash-2023-06-28_19.35.10-client.txt)

**Comment by TCLProject** [comment]
You appear to think this is an issue on my end. It's not - you simply have no mod (I'm looking at the mod list) that would extend potion IDs over 127. The minecraft limit is 32 - a lot of mods extend it to 127, because not much code is required. I'm not sure why you thought it was going to work without installing PotionExtension or the like. Install it, and the issue no longer appears.
