### ISSUE TITLE
Concentrate Time

### ISSUE THREAD

**Issue by SmaugNei** [TCLProject/ArsMagica2-5#33]

**Comment by SmaugNei** [comment]
Concentrated Time magic can be a bit of a contradiction since it may use light because of the sound and shape of the spell, which is contradictory to the book that says that the magical silver will always be from the respective tab. After many attempts trying to figure it out, I still haven't been able to, maybe I'm wrong, but I don't think so

**Comment by AirBurn0** [comment]
Concentrate Time can be unlocked via combining [Accelerate, Haste and Lingering](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/java/am2/spell/SpellUnlockManager.java#L54C1-L55C1);
And despite the fact that the compendium [clearly states](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_en_US.xml#L3127C359-L3127C359) that: "All parts required to unlock a silver skill will be in the same tree as the silver skill itself", this is true ONLY for pre AM2.5 silver spells; and new ones are an exception to this rule: Concentrate Time, Dilute Time, Fortify Time.

It may be worth updating the wording in the Compendium, since the rule has become obsolete and makes no sense anymore.

**Comment by SmaugNei** [comment]
Could you tell me how to get Fractal Fragment and Spatial star too, I'm from Brazil and I don't understand much English, sorry

**Comment by AirBurn0** [comment]
Github Issues is not the place for FAQ (it's for code and bugs discussions), so try asking around on [discord server](https://discord.com/invite/jXzrqPGcp3).

[Fractal Fragment](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_en_US.xml#L886) can be obtained via killing "[Hallucination endermites](https://github.com/TCLProject/ArsMagica2-5/blob/master/src/main/java/am2/entities/EntityHallucination.java)" (try magic damage spells) or "trading" (right click on them with Spatial Star) with "[Hallucination endermans](https://github.com/TCLProject/ArsMagica2-5/blob/master/src/main/java/am2/entities/EntityHallucination.java)" like Compendium says. Those mobs will spawn with some chance if you [drink Astrocalis in End dimension](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_en_US.xml#L1354).

[Spatial star](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_en_US.xml#L851C37-L851C37) can be lured out from Void in End dimension with [Arcane Fishing Rod](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_en_US.xml#L1416) when [it's full moon night in Overworld](https://github.com/TCLProject/ArsMagica2-5/blob/a0cdcb58cac0b9ceccc8283c06d28ca1d7ef025e/src/main/java/am2/entities/EntityFishHookArcane.java#L415).

Someday my friend will come out of his drinking bout and edit the AM2 wiki. But for today we can only independently explore the mod / read the code.
