### ISSUE TITLE
[1.5.0] Sunstone feels too rare

### ISSUE THREAD

**Issue by Not-February** [TCLProject/ArsMagica2-5#8]
I've checked overworld pools as well as the Nether. There is no sunstone ore to be found either inside lava pools themselves or even _near_ them.

Using default config values for sunstone generation, and reproduced with nothing but this mod and AnimationAPI(its dependency).

Forge 10.13.4.1614
AnimationAPI 1.7.10-1.2.4
Ars Magica 2 1.5.0 hotfixed version from Modrinth

**Comment by Not-February** [comment]
Since posting this, I've found a total of 3 sunstone ore in overworld lava pools after traveling thousands of blocks. It's there, but it feels a little too rare.

It also still feels weird that I haven't seen any at all in the Nether.

**Comment by TCLProject** [comment]
That's certainly strange that you didn't spot any in the Nether, but unless disabled somehow it should spawn there, mostly under the lava.
There are four parameters of sunstone gen you can tweak in the config: the min and max height, the vein size, and the rarity (frequency). If you feel they are too low, you are certainly welcome to change them for yourself.
As for the defaults, I don't think I have changed its default frequency, but if I have (again, I don't remember doing so), it's only because I believe its rarity should reflect its power in spell casting.
